"""add roles

Revision ID: dec84a0b1ca9
Revises: 3806f779fd92
Create Date: 2025-09-13 22:26:34.261993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dec84a0b1ca9"
down_revision: Union[str, Sequence[str], None] = "3806f779fd92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum("user", "admin", name="role")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column("role", sa.Enum("USER", "ADMIN", name="role"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
